export type DefaultTask = { text: string; month: string };
export type DefaultRole = { title: string; tasks: DefaultTask[] };

export const PLAYBOOK_DEFAULTS: DefaultRole[] = [
  {
    title: "School Lead",
    tasks: [
      // July
      { month: "July", text: "Organize team kickoff meeting" },
      { month: "July", text: "Fill out School Info Tracker" },
      { month: "July", text: "Contact your alumni" },
      { month: "July", text: "APPS OPEN JULY 29" },
      { month: "July", text: "Make team Slack" },
      { month: "July", text: "Assign team roles — Fill out and share Assigned Team Roles" },
      { month: "July", text: "Assign timelines" },
      { month: "July", text: "Figure out if anyone besides Sourcing Champ needs LinkedIn Recruiter" },
      { month: "July", text: 'Read "What Orr Recruits For" INTERNAL DOC' },
      { month: "July", text: "Begin to plan on-campus visits" },
      // August
      { month: "August", text: "Apps are live!" },
      { month: "August", text: "Recruitment Training" },
      { month: "August", text: "MM — Tools for each role; work time to think through strategy as a team" },
      { month: "August", text: "Continue to break down sourced names into team groups of 10" },
      { month: "August", text: "Fellows do campus visits — 2 days per school team" },
      { month: "August", text: "Supplement with online webinars" },
      { month: "August", text: "PACK YOUR DAY ON CAMPUS — how do you go to campus only 2 days but do everything you can?" },
      { month: "August", text: "Check in on team members — add support to those who need help with tasks" },
      { month: "August", text: "Monitor progress and adjust strategies as needed" },
      { month: "August", text: "Start reviewing resumes" },
      // September
      { month: "September", text: "Continue to break down sourced names into team groups of 10" },
      { month: "September", text: "Fellows continue on-campus visits" },
      { month: "September", text: "Supplement with online webinars" },
      { month: "September", text: "PACK YOUR DAY ON CAMPUS" },
      { month: "September", text: "Check in on team members — add support to those who need help" },
      { month: "September", text: "Text assigned candidates for last push — Sept 25/26" },
      { month: "September", text: "Read about reviewing resumes and DEI principals" },
      { month: "September", text: "Review resumes — assigned on the recruitment dashboard" },
    ],
  },
  {
    title: "Professor Outreach",
    tasks: [
      // July
      { month: "July", text: "Identify key professors and faculty for collaboration" },
      { month: "July", text: "Read about best practices for outreach" },
      { month: "July", text: "Read relevant pages from handbook" },
      // August
      { month: "August", text: "Identify key professors and faculty for collaboration" },
      { month: "August", text: "Learn how to use mail merge" },
      { month: "August", text: "Reach out to professors and faculty for collaboration" },
      { month: "August", text: "Use templates for emails if needed" },
      { month: "August", text: "Encourage faculty to share application information with students" },
      { month: "August", text: "Ask professors for lists of students who would be good Orr Fellows" },
      { month: "August", text: "Promote upcoming social events for candidates" },
      { month: "August", text: "Start reviewing resumes" },
      // September
      { month: "September", text: "Follow up with profs that haven't been in contact" },
      { month: "September", text: "Schedule in-class visits" },
      { month: "September", text: "Ask different professors for lists of students who would be good Orr Fellows" },
      { month: "September", text: "Work with Campus Champ, Social Organizer, and Ambassador to schedule in-class presentations" },
      { month: "September", text: "Review resumes" },
      { month: "September", text: "Text assigned candidates for last push — Sept 25/26" },
    ],
  },
  {
    title: "Sourcing Champion",
    tasks: [
      // July
      { month: "July", text: "Research sourcing methods and tools" },
      { month: "July", text: "Read about LinkedIn Recruiter" },
      { month: "July", text: "Read about Handshake" },
      { month: "July", text: 'Read "What Orr Recruits For" INTERNAL DOC' },
      { month: "July", text: "Read relevant pages from handbook" },
      // August
      { month: "August", text: "Research sourcing methods and tools" },
      { month: "August", text: "Learn how to use mail merge" },
      { month: "August", text: "Get LinkedIn Recruiter" },
      { month: "August", text: "Use templates for outreach" },
      { month: "August", text: "Source candidates!" },
      { month: "August", text: "Check on other team members sourcing — especially 1st years with connections" },
      { month: "August", text: "Organize sourcing from org outreach and prof outreach" },
      { month: "August", text: "Start reviewing resumes" },
      // September
      { month: "September", text: "Continue with follow-up to those that have been sourced" },
      { month: "September", text: "Go to campus!" },
      { month: "September", text: "Support DEI Ambassador to help capitalize on sourced groups that are underrepresented" },
      { month: "September", text: "Review resumes" },
      { month: "September", text: "Text assigned candidates for last push — Sept 25/26" },
    ],
  },
  {
    title: "Student Organization Outreach",
    tasks: [
      // July
      { month: "July", text: "Identify relevant student organizations for partnership" },
      { month: "July", text: "Read about best practices for outreach" },
      { month: "July", text: "Read relevant pages from handbook" },
      { month: "July", text: 'Read "What Orr Recruits For" INTERNAL DOC' },
      // August
      { month: "August", text: "Identify relevant student organizations for partnership" },
      { month: "August", text: "Learn how to use mail merge" },
      { month: "August", text: "Use templates for emails if needed" },
      { month: "August", text: "Promote upcoming social events for candidates" },
      { month: "August", text: "Start reviewing resumes" },
      // September
      { month: "September", text: "Promote upcoming social events for candidates" },
      { month: "September", text: "Work with DEI Ambassador to identify/connect with orgs you have not yet or are missing on campus" },
      { month: "September", text: "Go to campus!" },
      { month: "September", text: "Work with Campus Champ, Social Organizer, and Ambassador to schedule org presentations" },
      { month: "September", text: "Review resumes" },
    ],
  },
  {
    title: "Campus Champion",
    tasks: [
      // July
      { month: "July", text: "Research on-campus promotional opportunities" },
      { month: "July", text: "Read about best practices for outreach" },
      { month: "July", text: "Read about Handshake" },
      { month: "July", text: 'Read "What Orr Recruits For" INTERNAL DOC' },
      { month: "July", text: "Read relevant pages from handbook" },
      // August
      { month: "August", text: "Research on-campus promotional opportunities" },
      { month: "August", text: "Learn how to use mail merge" },
      { month: "August", text: "Choose which career fairs your team should attend" },
      { month: "August", text: "Curate webinars if applicable in addition to career fairs" },
      { month: "August", text: "Look into opportunities associated with career fair — backpack check, promoted content" },
      { month: "August", text: "Post events and activities to your school's Handshake" },
      { month: "August", text: "Identify and reserve spaces for on-campus promotional events" },
      { month: "August", text: "Begin on-campus promotions, distribute flyers and posters" },
      { month: "August", text: "Promote upcoming social events for candidates" },
      { month: "August", text: "Start reviewing resumes" },
      // September
      { month: "September", text: "Resend on-campus promotions, distribute flyers and posters to partners" },
      { month: "September", text: "Work with Social Organizer to make scheduled assignments for team members when on campus" },
      { month: "September", text: "Execute career fair" },
      { month: "September", text: "When on campus, foster relationships for future years" },
      { month: "September", text: "Assign others on the team to work events — those who would be AWESOME at it!" },
      { month: "September", text: "Go to campus — be the lead for your team of event folks" },
      { month: "September", text: "Review resumes" },
      { month: "September", text: "Text assigned candidates for last push — Sept 25/26" },
    ],
  },
  {
    title: "Social Organizer",
    tasks: [
      // July
      { month: "July", text: "Plan social events for team bonding and candidate engagement" },
      { month: "July", text: "Read about best practices for outreach" },
      { month: "July", text: "Read about Handshake" },
      { month: "July", text: 'Read "What Orr Recruits For" INTERNAL DOC' },
      { month: "July", text: "Read relevant pages from handbook" },
      // August
      { month: "August", text: "Plan social events for team bonding and candidate engagement" },
      { month: "August", text: "Learn how to use mail merge" },
      { month: "August", text: "Create the strategy of how to pack the 2 days on campus with the most effective events" },
      { month: "August", text: "Non-career fair events — think tabling, doughnuts at a coffee shop, networking at a bar, etc." },
      { month: "August", text: "Set up events/professor talks/tabling etc. for your 2 days on campus" },
      { month: "August", text: "Coordinate with alumni who can come to campus visits" },
      { month: "August", text: "Post events and activities to your school's Handshake" },
      { month: "August", text: "Promote upcoming social events for candidates" },
      { month: "August", text: "Get spaces paid for and scheduled for events" },
      { month: "August", text: "Make an exclusive event for when on campus" },
      { month: "August", text: "Start reviewing resumes" },
      // September
      { month: "September", text: "Promote upcoming social events for candidates" },
      { month: "September", text: "Get spaces paid for and scheduled for events" },
      { month: "September", text: "Make an exclusive event for when on campus" },
      { month: "September", text: "Assign others on the team to work events — those who would be AWESOME at it!" },
      { month: "September", text: "Go to campus — be the lead for your team of event folks" },
      { month: "September", text: "Work with Campus Champ to make scheduled assignments for team members when on campus" },
      { month: "September", text: "Work with Campus Champ and Ambassador to schedule in-class presentations" },
      { month: "September", text: "When on campus, foster relationships for future years" },
      { month: "September", text: "Review resumes" },
      { month: "September", text: "Text assigned candidates for last push — Sept 25/26" },
    ],
  },
  {
    title: "Orr Fellowship Ambassador",
    tasks: [
      // July
      { month: "July", text: "Collect materials and stories to share with candidates" },
      { month: "July", text: "Read relevant pages from handbook" },
      { month: "July", text: "Work with 1st year to decide how your roles should work together" },
      { month: "July", text: 'Read "What Orr Recruits For" INTERNAL DOC' },
      // August
      { month: "August", text: "Collect materials and stories to share with candidates" },
      { month: "August", text: "Learn how to use mail merge" },
      { month: "August", text: '"Close the deal" with getting people to apply' },
      { month: "August", text: "1st years will pass sourced people to you — talk with possible applicants at coffee chats, on calls, over email, etc." },
      { month: "August", text: "You've been in Orr for over a year — be the voice to explain what Orr is really like" },
      { month: "August", text: 'Follow up with each person you "own" to make sure they have applied and done the steps after application' },
      { month: "August", text: "Use templates for outreach" },
      { month: "August", text: "Help with lists of people flagged as highly eligible candidates" },
      { month: "August", text: "Promote upcoming social events for candidates" },
      { month: "August", text: "Start reviewing resumes" },
      // September
      { month: "September", text: "Work with DEI Ambassador to connect 1:1 with students/groups on campus who are underrepresented" },
      { month: "September", text: "Share application tips and advice from past fellows" },
      { month: "September", text: "Make sure team is prepared to talk to folks on campus — help with elevator pitches/messages for career fair, tabling, etc." },
      { month: "September", text: "Execute when visiting on campus" },
      { month: "September", text: "Support team when engaging with candidates — e.g. schedule coffee dates" },
      { month: "September", text: "Do LinkedIn follow-up with candidates" },
      { month: "September", text: "Review resumes" },
      { month: "September", text: "Text assigned candidates for last push — Sept 25/26" },
    ],
  },
  {
    title: "DEI Ambassador",
    tasks: [
      // July
      { month: "July", text: "Develop strategies for reaching diverse candidate groups" },
      { month: "July", text: "Read about best practices for outreach" },
      { month: "July", text: "Read about Handshake" },
      { month: "July", text: "Go through past DEI vault and update" },
      { month: "July", text: 'Read "What Orr Recruits For" INTERNAL DOC' },
      { month: "July", text: "Read relevant pages in handbook" },
      { month: "July", text: "Read about DEI Team, Goals, Benchmarks and Tracking" },
      // August
      { month: "August", text: "Develop strategies for reaching diverse candidate groups" },
      { month: "August", text: "Learn how to use mail merge" },
      { month: "August", text: "Help the Student Organization Outreach Role curate list of orgs on campus targeting underrepresented students" },
      { month: "August", text: "Curate your school's fall activities document for more information on DEI engagement opportunities" },
      { month: "August", text: "Own your team's understanding and engagement with our DEI principals — DEI Team, Goals, Benchmarks and Tracking" },
      { month: "August", text: "Start reviewing resumes" },
      { month: "August", text: "Promote upcoming social events for candidates" },
      // September
      { month: "September", text: "Evaluate DEI contacts and progress — meet with each teammate to see how their role can be better" },
      { month: "September", text: "Reach out to spaces on campus that still need to be contacted" },
      { month: "September", text: "Follow up with promising spaces/groups" },
      { month: "September", text: "Execute visits to spaces when on campus" },
      { month: "September", text: "When on campus, lay groundwork for future years" },
      { month: "September", text: "Review resumes" },
      { month: "September", text: "Text assigned candidates for last push — Sept 25/26" },
    ],
  },
  {
    title: "Oct/Nov Milestones",
    tasks: [
      { month: "Oct/Nov", text: "Remind your candidates to sign up for optional fORRum (9/29, 9/30)" },
      { month: "Oct/Nov", text: "Check in with candidates on Oct. 3 — make sure they've gotten an email from Orr if they made it to the next stage" },
      { month: "Oct/Nov", text: "Text candidates on 10/5 — make sure they've signed up for BMI Interview by midnight" },
      { month: "Oct/Nov", text: "Check in with candidates on Oct. 17 — ROTC invite and Reapp sent" },
      { month: "Oct/Nov", text: "Offer to help candidates with re-app questions — essay, PI, resume resubmit" },
      { month: "Oct/Nov", text: "Text candidates on Oct. 21 — make sure they RSVP for ROTR by midnight" },
      { month: "Oct/Nov", text: "Text candidates on Oct. 21 — make sure they RSVP for ROTC by midnight" },
      { month: "Oct/Nov", text: "ROTR — Oct. 24, Evansville" },
      { month: "Oct/Nov", text: "ROTC — Oct. 23, Indianapolis + Streamed" },
      { month: "Oct/Nov", text: "Text candidates on Oct. 26 — reapplication due by midnight" },
      { month: "Oct/Nov", text: "Check in with candidates on Nov. 19 — Finalist Day, waitlist, none, or accept email" },
      { month: "Oct/Nov", text: "Text candidates to RSVP for Finalist Day — RSVP due 12/5" },
      { month: "Oct/Nov", text: "Help out at Finalist Day Dec. 5 — you'll be assigned a job on one shift" },
      { month: "Oct/Nov", text: "Make sure candidates know how to get costs offset for traveling (200+ miles) and virtual ROTC eligibility" },
    ],
  },
];
